---
title: "47987_MY461_Week2"
author: '47987'
date: "2023-02-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Logistics

Downloading the appropriate libraries:
```{r}
install.packages("igraph")
install.packages("igraphdata")
install.packages("tidygraph")
library(igraph)
library(igraphdata)
library(tidygraph)
```

Feeding in the data:
```{r}

```

```{r}
g1 <- make_graph(edges = c("	Aaron	"	,	"	Misaal	"	,
"	Adetayo	"	,	"	Tessa	"	,
"	Aishat	"	,	"	Ona	"	,
"	Ajax	"	,	"	Adetayo	"	,
"	Alaweya	"	,	"	Damilare	"	,
"	Alexa	"	,	"	Alexa	"	,
"	Alexandra	"	,	"	Schera	"	,
"	Alina	"	,	"	Alexa	"	,
"	Amina	"	,	"	Paulina	"	,
"	Amy (Sathya +1)	"	,	"	Sathya	"	,
"	Anesu	"	,	"	Tessa	"	,
"	Ants	"	,	"	Michael	"	,
"	Anwar	"	,	"	Michael	"	,
"	April	"	,	"	Paulina	"	,
"	Aurora	"	,	"	Axel	"	,
"	Axel	"	,	"	Mahilet	"	,
"	Baba	"	,	"	Alexa	"	,
"	Bami	"	,	"	Alexa	"	,
"	Barns	"	,	"	Chelsea	"	,
"	Bernita	"	,	"	Malika	"	,
"	Cal1sto	"	,	"	Finch	"	,
"	Chelsea	"	,	"	Tessa	"	,
"	Chloe	"	,	"	Malika	"	,
"	CK	"	,	"	Alexa	"	,
"	Clive	"	,	"	Alexa	"	,
"	Dave	"	,	"	Tallulah	"	,
"	David	"	,	"	Schera	"	,
"	Diana	"	,	"	Alexa	"	,
"	Dillon	"	,	"	Toren	"	,
"	Dimeji	"	,	"	Isaac	"	,
"	Divine	"	,	"	Baba	"	,
"	Dom	"	,	"	Tessa	"	,
"	Dot	"	,	"	Tessa	"	,
"	Drvcilla	"	,	"	Sathya	"	,
"	Ebenezer	"	,	"	Divine	"	,
"	Edd	"	,	"	Damilare	"	,
"	Elijah	"	,	"	Alina	"	,
"	Eman	"	,	"	Alexa	"	,
"	Eman Notts	"	,	"	Mehmet	"	,
"	Emma	"	,	"	Alexa	"	,
"	Enzo	"	,	"	Sheck East	"	,
"	Ester	"	,	"	Simba	"	,
"	Fanuel	"	,	"	Toye	"	,
"	Favour	"	,	"	Tessa	"	,
"	Feranmi	"	,	"	Axel	"	,
"	Fin	"	,	"	Alexa	"	,
"	Finch	"	,	"	Paulina	"	,
"	Floraine	"	,	"	Tallulah	"	,
"	Gbnga	"	,	"	Isaac	"	,
"	George	"	,	"	Alaweya	"	,
"	George +1	"	,	"	George	"	,
"	Grace	"	,	"	Alexa	"	,
"	Grace	"	,	"	Chloe	"	,
"	Habib	"	,	"	Baba	"	,
"	Hama	"	,	"	Baba	"	,
"	Henry	"	,	"	Ants	"	,
"	Henry +1	"	,	"	Henry	"	,
"	Iman	"	,	"	Alexa	"	,
"	India	"	,	"	Keziah	"	,
"	Isaac	"	,	"	Alexa	"	,
"	J'Leise	"	,	"	Alexa	"	,
"	Jackie	"	,	"	Sanu	"	,
"	Jaida	"	,	"	Alexa	"	,
"	Jan	"	,	"	Ajax	"	,
"	Javan	"	,	"	Goldsmiths	"	,
"	Jean Michel	"	,	"	Alexa	"	,
"	Jen	"	,	"	Alexa	"	,
"	Jess	"	,	"	Ester	"	,
"	Jojo	"	,	"	Valentine	"	,
"	KD22	"	,	"	Edd	"	,
"	Kellendria	"	,	"	Alexa	"	,
"	Kenny	"	,	"	Alexa	"	,
"	Keziah	"	,	"	Toren	"	,
"	Kiya	"	,	"	Grace I	"	,
"	Kutch	"	,	"	Alexa	"	,
"	Lashai	"	,	"	Paul	"	,
"	Laura	"	,	"	Alexa	"	,
"	Lekky	"	,	"	Alexa	"	,
"	Len	"	,	"	Bami	"	,
"	Lewis	"	,	"	Fanuel	"	,
"	Lola	"	,	"	Alexa	"	,
"	Lola	"	,	"	Aishat	"	,
"	Lorraine	"	,	"	Sarah	"	,
"	Lucille +1	"	,	"	Kenny	"	,
"	Lydia	"	,	"	Nyat	"	,
"	Lyndon	"	,	"	Michael Lemoru	"	,
"	Mahilet	"	,	"	Alexa	"	,
"	Mahlahsia	"	,	"	Alexa	"	,
"	Malika	"	,	"	Grace I	"	,
"	Mark	"	,	"	Ming	"	,
"	Marvin	"	,	"	Tito	"	,
"	Masud	"	,	"	Aaron	"	,
"	Megan	"	,	"	Alexa	"	,
"	Megan +1	"	,	"	Megan	"	,
"	Mehmet	"	,	"	Eman	"	,
"	Melisa	"	,	"	Alina	"	,
"	Michael	"	,	"	Eman Notts	"	,
"	Michael Lemoru	"	,	"	Ants	"	,
"	Ming	"	,	"	Tallulah	"	,
"	Misaal	"	,	"	Javan	"	,
"	Misuka	"	,	"	Javan	"	,
"	Mubarak	"	,	"	Alexa	"	,
"	Musti	"	,	"	Lekky	"	,
"	Nadine	"	,	"	Gbnga	"	,
"	Nanya	"	,	"	Met Online	"	,
"	Naomi	"	,	"	Henry	"	,
"	Nat	"	,	"	Alexa	"	,
"	Neyat	"	,	"	Seghen	"	,
"	Niz +1	"	,	"	Niz	"	,
"	Nur	"	,	"	Alexa	"	,
"	Nyat	"	,	"	Neyat	"	,
"	Aminat	"	,	"	Ola	"	,
"	Ona	"	,	"	Aishat	"	,
"	Pabz	"	,	"	Grace	"	,
"	Paul	"	,	"	Lashai	"	,
"	Paulina	"	,	"	Alaweya	"	,
"	Philip/ Chad +1	"	,	"	Seun	"	,
"	Pima	"	,	"	Alexa	"	,
"	Precious	"	,	"	Alexa	"	,
"	Rachel	"	,	"	Megan	"	,
"	Rahel	"	,	"	Michael Lemoru	"	,
"	Reem	"	,	"	Toye	"	,
"	Reti	"	,	"	Yana	"	,
"	Rhoda	"	,	"	Tatenda	"	,
"	Roxanne	"	,	"	Chelsea	"	,
"	Saff	"	,	"	Emma	"	,
"	Sanu +1	"	,	"	Sanu	"	,
"	Sara	"	,	"	Lorraine	"	,
"	Sathya	"	,	"	Alexa	"	,
"	Schera	"	,	"	Met Online	"	,
"	Seghen	"	,	"	Rhoda	"	,
"	Seun	"	,	"	Nyat	"	,
"	Seun from summer	"	,	"	Alexa	"	,
"	Sheck East	"	,	"	Chelsea	"	,
"	Simba	"	,	"	Tatenda	"	,
"	Sosa	"	,	"	Alexa	"	,
"	Sosa +1	"	,	"	Sosa	"	,
"	Sosa +2	"	,	"	Sosa	"	,
"	Steph	"	,	"	Alaweya	"	,
"	Sundus	"	,	"	Goldsmiths	"	,
"	Sushi	"	,	"	Nyat	"	,
"	Talia	"	,	"	Tamia	"	,
"	Tallulah	"	,	"	Alexa	"	,
"	Tamia	"	,	"	Jen	"	,
"	Tatenda	"	,	"	Tessa	"	,
"	Tessa	"	,	"	Alex	"	,
"	Thomas	"	,	"	Elijah	"	,
"	Timi (Tobs +1)	"	,	"	Tobss	"	,
"	Tito	"	,	"	Aishat	"	,
"	Tobss	"	,	"	Alexa	"	,
"	Tom	"	,	"	Alexa	"	,
"	Toneh	"	,	"	Jen	"	,
"	Toren	"	,	"	Nyat	"	,
"	Toye	"	,	"	Tessa	"	,
"	Trinite	"	,	"	Jess	"	,
"	Tyra	"	,	"	Naomi	"	,
"	Valentina	"	,	"	Tessa	"	,
"	Vicky	"	,	"	Grace	"	,
"	Wayne	"	,	"	Alina	"	,
"	Yana	"	,	"	Grace	"	,
"	Yasmin	"	,	"	Alexa	"	,
"	Yusuf	"	,	"	Seun	"	,
"	Zhane	"	,	"	Sosa	"	,
"	Zino	"	,	"	Alexa	"	),
                 directed = FALSE)

print(g1)
```

```{r}
plot.igraph(g1)
```

```{r}
as_edgelist(g1, names = TRUE)
V(g1)$names
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
